name: Continuous Integration

on:
  push:
    tags: ['*']
    branches: ['main']
  pull_request:
  workflow_dispatch:

env:
  verilator-version: v5.022
  verilator-install-dir: verilator-install

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: VirtusLab/scala-cli-setup@v1
        with:
          jvm: adopt:11
          apps: sbt giter8 # Feel free to delete giter8
      - name: Setup Mill
        run: |
          curl -L https://github.com/com-lihaoyi/mill/releases/download/0.12.5/0.12.5 > mill && chmod +x mill
# $! TODO we probably need to still install Verilator but $ are problems for giter8
      - name: Setup Dependencies
        run: |
          sudo apt-get install ccache
      - name: Get Cached Verilator
        id: get-cached-verilator
        uses: actions/cache@v4
        with:
          path: ${{ env.verilator-install-dir }}
          key: verilator-${{ env.verilator-version }}
      - name: Install Verilator
        if: steps.get-cached-verilator.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install git help2man perl python3 make autoconf g++ flex bison numactl perl-doc libfl-dev
          git clone https://github.com/verilator/verilator
          unset VERILATOR_ROOT
          cd verilator
          git checkout ${{ env.verilator-version  }}
          autoconf
          ./configure --prefix=$(pwd)/../${{ env.verilator-install-dir }}
          make
          make install
      - name: Set PATH
        run: |
          echo "$(pwd)/${{ env.verilator-install-dir }}/bin" >> $GITHUB_PATH
          echo VERILATOR_ROOT="$(pwd)/${{ env.verilator-install-dir }}/share/verilator" >> $GITHUB_ENV
          ln -sf $(pwd)/${{ env.verilator-install-dir }}/bin/verilator_bin $(pwd)/${{ env.verilator-install-dir }}/share/verilator/verilator_bin
      # Run g8 and replace all contents here with the output of g8
      - name: Run g8
        run: |
          g8 file://$PWD --name=test --organization=example -o ../test
          rm -rf *
          mv ../test/* .
      # Feel free to pick one or the other!$
      - name: SBT Test
        run: sbt test
      - name: mill Test
        run: ./mill _.test
